### ISSUE TITLE
Can not build on ubuntu 20.04

### ISSUE THREAD

**Issue by saiqulhaq-hh** [ImageMagick/ImageMagick6#355]
### ImageMagick version

6.9.13-19

### Operating system

Linux

### Operating system, version and so on

ubuntu 20.04

### Description

```
CCLD     utilities/animate
--
5179 | CCLD     utilities/conjure
5180 | CCLD     utilities/compare
5181 | CCLD     utilities/composite
5182 | /usr/bin/ld: magick/.libs/libMagickCore-6.Q16.so: undefined reference to `TIFFReadGPSDirectory'
5183 | collect*: error: ld returned 1 exit status
5184 | make[1]: *** [Makefile:7450: utilities/conjure] Error 1
5185 | make[1]: *** Waiting for unfinished jobs....
5186 | /usr/bin/ld: magick/.libs/libMagickCore-6.Q16.so: undefined reference to `TIFFReadGPSDirectory'
5187 | collect*: error: ld returned 1 exit status
5188 | make[1]: *** [Makefile:743*: utilities/animate] Error 1
5189 | /usr/bin/ld: magick/.libs/libMagickCore-6.Q16.so: undefined reference to `TIFFReadGPSDirectory'
5190 | collect*: error: ld returned 1 exit status
5191 | make[1]: *** [Makefile:7438: utilities/compare] Error 1
5192 | /usr/bin/ld: magick/.libs/libMagickCore-6.Q16.so: undefined reference to `TIFFReadGPSDirectory'
5193 | collect*: error: ld returned 1 exit status
5194 | make[1]: *** [Makefile:7444: utilities/composite] Error 1
5195 | make[1]: Leaving directory '/tmp/ImageMagick-6.9.13-19'
5196 | make: *** [Makefile:5699: all] Error *
5197 | The command '/bin/sh -c cd ImageMagick-6.9.13-19 && ./configure && make -j4 && make install && ldconfig' returned a non-zero code: *
```

It was fine with 6.9.13-17

### Steps to Reproduce

RUN wget https://imagemagick.org/download/releases/ImageMagick-6.9.13-19.tar.gz
RUN tar xvf ImageMagick-6.9.13-19.tar.gz
RUN cd ImageMagick-6.9.13-19 && ./configure && make -j4 && make install && ldconfig

### Images

![image](https://github.com/user-attachments/assets/ae1e962d-9b2a-4a8e-925a-ad9f2efa9f1e)

**Comment by dlemstra** [comment]
It looks like we are missing a patch that we made in ImageMagick 7 here. Will fix this later today.
